spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jdbc:postgresql://db.ubjabvpkpmpaeyonrohr.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]